version: "2"
linters:
  enable:
    - gosec
  disable:
    - staticcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
run:
  timeout: 5m
issues:
  exclude-rules:
    # Skip test files when running the gosec linter.
    - path: (.+)_test\.go
      linters:
        - gosec

